# Stubs for fastecdsa.tests (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..curve import P192, P224, P256, P384, P521, brainpoolP160r1, brainpoolP192r1, brainpoolP224r1, brainpoolP256r1, brainpoolP320r1, brainpoolP384r1, brainpoolP512r1, secp192k1, secp224k1, secp256k1
from typing import Any

CURVES: Any
