# Stubs for fastecdsa.tests.test_asn1 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..curve import P256
from ..keys import export_key, gen_keypair, import_key
from unittest import TestCase

class TestAsn1(TestCase):
    def test_generate_and_parse_pem(self) -> None: ...
