# Stubs for fastecdsa.tests.test_key_recovery (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..ecdsa import sign
from ..keys import gen_keypair, get_public_keys_from_sig
from unittest import TestCase

class TestKeyRecovery(TestCase):
    def test_key_recovery(self) -> None: ...
