# Stubs for fastecdsa.tests.test_key_encoding (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..curve import P256, secp192k1, secp256k1
from ..encoding.sec1 import InvalidSEC1PublicKey, SEC1Encoder
from ..point import Point
from unittest import TestCase

class TestEncodePublicKey(TestCase):
    def test_SEC1_encode_public_key(self) -> None: ...
    def test_SEC1_decode_public_key(self) -> None: ...
