# Stubs for fastecdsa.tests.test_brainpool_ecdh (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..curve import brainpoolP256r1, brainpoolP384r1, brainpoolP512r1
from unittest import TestCase

class TestBrainpoolECDH(TestCase):
    def test_256bit(self) -> None: ...
    def test_384bit(self) -> None: ...
    def test_512bit(self) -> None: ...
