# Stubs for fastecdsa.tests.test_nonce_generation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..util import RFC6979
from unittest import TestCase

class TestNonceGeneration(TestCase):
    def test_rfc_6979(self) -> None: ...
