# Stubs for fastecdsa.encoding (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import abc
from ..point import Point
from abc import abstractmethod
from typing import Any, Tuple


class KeyEncoder(metaclass=abc.ABCMeta):
    __metaclass__: Any = ...

    @staticmethod
    @abstractmethod
    def encode_public_key(Q: Point) -> Any:
        ...

    @staticmethod
    @abstractmethod
    def encode_private_key(d: int) -> Any:
        ...

    @staticmethod
    @abstractmethod
    def decode_public_key(data: Any) -> Point:
        ...

    @staticmethod
    @abstractmethod
    def decode_private_key(data: Any) -> Tuple[int, Point]:
        ...


class SigEncoder(metaclass=abc.ABCMeta):
    __metaclass__: Any = ...

    @staticmethod
    @abstractmethod
    def encode_signature(r: int, s: int) -> bytes:
        ...

    @staticmethod
    @abstractmethod
    def decode_signature(binary_data: bytes) -> Tuple[int, int]:
        ...
