# Stubs for fastecdsa.encoding.pem (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from . import KeyEncoder
from ..curve import Curve
from ..point import Point
from .asn1 import BIT_STRING, OBJECT_IDENTIFIER, OCTET_STRING, PARAMETERS, PUBLIC_KEY, SEQUENCE, asn1_ecpublickey, asn1_ecversion, asn1_oid, asn1_private_key, asn1_public_key, asn1_structure, parse_asn1_length
from typing import Any, Tuple

EC_PRIVATE_HEADER: str
EC_PRIVATE_FOOTER: str
EC_PUBLIC_HEADER: str
EC_PUBLIC_FOOTER: str


class PEMEncoder(KeyEncoder):
    ASN1_PARSED_DATA: Any = ...

    @staticmethod
    def encode_public_key(Q: Point) -> str:
        ...

    @staticmethod
    def encode_private_key(d: int, Q: Point = ..., curve: Curve = ...) -> str:
        ...

    @staticmethod
    def decode_public_key(pemdata: str, curve: Curve = ...) -> Point:
        ...

    @staticmethod
    def decode_private_key(pemdata: str) -> Tuple[int, Point]:
        ...
