# Stubs for fastecdsa.encoding.sec1 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from . import KeyEncoder
from ..curve import Curve
from ..point import Point
from ..util import mod_sqrt
from .util import bytes_to_int, int_bytelen, int_to_bytes
from typing import Any

class InvalidSEC1PublicKey(Exception): ...

class SEC1Encoder(KeyEncoder):
    @staticmethod
    def encode_public_key(point: Point, compressed: bool=...) -> bytes: ...
    @staticmethod
    def decode_public_key(key: bytes, curve: Curve) -> Point: ...
    @staticmethod
    def encode_private_key(d: Any) -> None: ...
    @staticmethod
    def decode_private_key(data: Any) -> None: ...
