# Stubs for fastecdsa._ecdsa (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def sign(*args, **kwargs) -> Any: ...
def verify(*args, **kwargs) -> Any: ...
