# Stubs for fastecdsa.curve (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any


class Curve:
    name: Any = ...
    p: Any = ...
    a: Any = ...
    b: Any = ...
    q: Any = ...
    gx: Any = ...
    gy: Any = ...
    oid: Any = ...

    def __init__(
        self,
        name: str,
        p: int,
        a: int,
        b: int,
        q: int,
        gx: int,
        gy: int,
        oid: bytes = ...
    ) -> None:
        ...

    @classmethod
    def get_curve_by_oid(cls: Any, oid: bytes) -> Any:
        ...

    def is_point_on_curve(self, P: Any) -> bool:
        ...

    def evaluate(self, x: int) -> int:
        ...

    @property
    def G(self):
        ...


P192: Any
P224: Any
P256: Any
P384: Any
P521: Any
secp192k1: Any
secp224k1: Any
secp256k1: Any
brainpoolP160r1: Any
brainpoolP192r1: Any
brainpoolP224r1: Any
brainpoolP256r1: Any
brainpoolP320r1: Any
brainpoolP384r1: Any
brainpoolP512r1: Any
