# Stubs for fastecdsa.curvemath (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def add(*args, **kwargs) -> Any: ...
def mul(*args, **kwargs) -> Any: ...
