# Stubs for fastecdsa.keys (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .curve import Curve, P256
from .ecdsa import verify
from .encoding.pem import PEMEncoder
from .point import Point
from .util import mod_sqrt, msg_bytes
from typing import Any, Tuple


def gen_keypair(curve: Curve) -> Tuple[int, Point]:
    ...


def gen_private_key(curve: Curve, randfunc: Any = ...) -> int:
    ...


def get_public_key(d: int, curve: Curve) -> Point:
    ...


def get_public_keys_from_sig(
    sig: Tuple[int, int], msg: Any, curve: Curve = ..., hashfunc: Any = ...
) -> Tuple[Point, Point]:
    ...


def export_key(
    key: Any, curve: Curve = ..., filepath: str = ..., encoder: Any = ...
) -> Any:
    ...


def import_key(
    filepath: str, curve: Curve = ..., public: bool = ..., decoder: Any = ...
) -> Any:
    ...
